version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
