export enum ConfigKeys {
  JWT_SECRET = 'JWT_SECRET',
  TOKEN_EXPIRATION_TIME = 'TOKEN_EXPIRATION_TIME',
  DEFAULT_LIMIT = 'DEFAULT_LIMIT',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'MYSQL_USER',
  DB_PASSWORD = 'MYSQL_ROOT_PASSWORD',
  DB_DATABASE = 'MYSQL_DATABASE'
}
